apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-config
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}
type: Opaque
stringData:
  {{- range $key, $secret := .Values.secrets }}
  {{ $key }}: {{ $secret | quote }}
  {{- end }}
